export const apiResponse = {
    "total_count": 186137,
    "incomplete_results": false,
    "items": [
        {
            "login": "MaxCodeXTC",
            "id": 53144281,
            "node_id": "MDQ6VXNlcjUzMTQ0Mjgx",
            "avatar_url": "https://avatars.githubusercontent.com/u/53144281?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaxCodeXTC",
            "html_url": "https://github.com/MaxCodeXTC",
            "followers_url": "https://api.github.com/users/MaxCodeXTC/followers",
            "following_url": "https://api.github.com/users/MaxCodeXTC/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaxCodeXTC/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaxCodeXTC/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaxCodeXTC/subscriptions",
            "organizations_url": "https://api.github.com/users/MaxCodeXTC/orgs",
            "repos_url": "https://api.github.com/users/MaxCodeXTC/repos",
            "events_url": "https://api.github.com/users/MaxCodeXTC/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaxCodeXTC/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "DEVBOX10",
            "id": 740576,
            "node_id": "MDQ6VXNlcjc0MDU3Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/740576?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/DEVBOX10",
            "html_url": "https://github.com/DEVBOX10",
            "followers_url": "https://api.github.com/users/DEVBOX10/followers",
            "following_url": "https://api.github.com/users/DEVBOX10/following{/other_user}",
            "gists_url": "https://api.github.com/users/DEVBOX10/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/DEVBOX10/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/DEVBOX10/subscriptions",
            "organizations_url": "https://api.github.com/users/DEVBOX10/orgs",
            "repos_url": "https://api.github.com/users/DEVBOX10/repos",
            "events_url": "https://api.github.com/users/DEVBOX10/events{/privacy}",
            "received_events_url": "https://api.github.com/users/DEVBOX10/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maxprofs-llcio",
            "id": 50819790,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjUwODE5Nzkw",
            "avatar_url": "https://avatars.githubusercontent.com/u/50819790?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maxprofs-llcio",
            "html_url": "https://github.com/maxprofs-llcio",
            "followers_url": "https://api.github.com/users/maxprofs-llcio/followers",
            "following_url": "https://api.github.com/users/maxprofs-llcio/following{/other_user}",
            "gists_url": "https://api.github.com/users/maxprofs-llcio/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maxprofs-llcio/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maxprofs-llcio/subscriptions",
            "organizations_url": "https://api.github.com/users/maxprofs-llcio/orgs",
            "repos_url": "https://api.github.com/users/maxprofs-llcio/repos",
            "events_url": "https://api.github.com/users/maxprofs-llcio/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maxprofs-llcio/received_events",
            "type": "Organization",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "maxbyz",
            "id": 13717208,
            "node_id": "MDQ6VXNlcjEzNzE3MjA4",
            "avatar_url": "https://avatars.githubusercontent.com/u/13717208?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/maxbyz",
            "html_url": "https://github.com/maxbyz",
            "followers_url": "https://api.github.com/users/maxbyz/followers",
            "following_url": "https://api.github.com/users/maxbyz/following{/other_user}",
            "gists_url": "https://api.github.com/users/maxbyz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/maxbyz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/maxbyz/subscriptions",
            "organizations_url": "https://api.github.com/users/maxbyz/orgs",
            "repos_url": "https://api.github.com/users/maxbyz/repos",
            "events_url": "https://api.github.com/users/maxbyz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/maxbyz/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "Max4aters",
            "id": 26367220,
            "node_id": "MDQ6VXNlcjI2MzY3MjIw",
            "avatar_url": "https://avatars.githubusercontent.com/u/26367220?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Max4aters",
            "html_url": "https://github.com/Max4aters",
            "followers_url": "https://api.github.com/users/Max4aters/followers",
            "following_url": "https://api.github.com/users/Max4aters/following{/other_user}",
            "gists_url": "https://api.github.com/users/Max4aters/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Max4aters/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Max4aters/subscriptions",
            "organizations_url": "https://api.github.com/users/Max4aters/orgs",
            "repos_url": "https://api.github.com/users/Max4aters/repos",
            "events_url": "https://api.github.com/users/Max4aters/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Max4aters/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        },
        {
            "login": "MaxMax2016",
            "id": 16432329,
            "node_id": "MDQ6VXNlcjE2NDMyMzI5",
            "avatar_url": "https://avatars.githubusercontent.com/u/16432329?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MaxMax2016",
            "html_url": "https://github.com/MaxMax2016",
            "followers_url": "https://api.github.com/users/MaxMax2016/followers",
            "following_url": "https://api.github.com/users/MaxMax2016/following{/other_user}",
            "gists_url": "https://api.github.com/users/MaxMax2016/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MaxMax2016/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MaxMax2016/subscriptions",
            "organizations_url": "https://api.github.com/users/MaxMax2016/orgs",
            "repos_url": "https://api.github.com/users/MaxMax2016/repos",
            "events_url": "https://api.github.com/users/MaxMax2016/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MaxMax2016/received_events",
            "type": "User",
            "site_admin": false,
            "score": 1.0
        }
    ]
}